name: bluebeetle
favicon: null
layout_spectrum: 0.90482
typography_spectrum: 0.63321
title: A day in the life of a bleu beetle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffffe'
    - '#0d0d0d'
    - '#bfb9a7'
    - '#2d4e72'
    - '#a65a5b'
  brandStrength: 0.5
  lightness: 0.625
  saturation: 0.3125
  rhythmicContrast: 0.75
purpose: []
