name: bluebeetle
favicon: null
layout_spectrum: 0.5757291147019714
typography_spectrum: 0.15653217118233442
title: A day in the life of a bleu beetle
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.3356018611229956
  lightness: 0.49545711767859757
  saturation: 0.5040736275259405
  rhythmicContrast: 0.805290080839768
purpose: []
